### PR TITLE
Update duckdb-version to 0.9.0 from 0.8.1

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Comment by v1gnesh** [comment]
@IgortodorovskiIBM looks like DuckDB 0.9 just landed.
Could you try a manual build in CI for this PR please?

**Comment by IgorTodorovskiIBM** [comment]
I'm working on a github action that will be able to trigger a build on jenkins and capture the result as a github status check, I'd like to try it on duckdb first, should be done tomorrow or by Friday.

**Comment by IgorTodorovskiIBM** [comment]
The github action seems to be working now. The duckdb run is currently ongoing, I'll make some enhancements tomorrow to display the current build progress

**Comment by IgorTodorovskiIBM** [comment]
Looks like it failed :) Let's try again
/run tests

**Comment by v1gnesh** [comment]
Should the build artifact be uploaded here as a pre-release?
If so, are any steps required to go from pre-release to actual release?

**Comment by IgorTodorovskiIBM** [comment]
/run tests

> Should the build artifact be uploaded here as a pre-release? If so, are any steps required to go from pre-release to actual release?
We could probably enhance is to upload a pre-release artifact to github, it's currently accessible in jenkins but not via github.

Once the PR gets merged, we'll get a release created...as long as it builds and we get the expected number of passes, speaking of which...we should implement this function https://github.com/ZOSOpenTools/duckdbport/blob/main/buildenv#L29. I can help with that if needed.

**Pull request merged**
